### ISSUE TITLE
Does it compile?

### ISSUE THREAD

**Issue by gowthamnatarajan** [deeplearning4j/gym-java-client#4]
This is not compiling. For example ArrayObservationSpace does not implement the methods in ObservationSpace

**Comment by huitseeker** [comment]
The getters required in `ObservationSpace` are implemented through the `@Value` class annotation in [Lombok](https://projectlombok.org/features/Value.html). I can't reproduce your compilation failure on  a0f22c388dc13d3207b6a4880b147e77e281f8be
